package view;

import db.DbConnection;
import exception.EmptyFieldException;
import exception.IDnotValidException;
import exception.NotFoundException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ItemReturn;
import util.IDChecker;
import util.IdCounter;

public class ReturnItemForm extends javax.swing.JFrame {

    String userName; //user name for window

    String returnID;
    String returnDate;

    public ReturnItemForm(String userName) {
        initComponents();

        this.userName = userName;
        return_userName.setText(userName); //set user name

        LocalDate date = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        returnDate = date.format(formatter);

        IdCounter counter = new IdCounter();
        returnID = counter.getId("R", "return_id", "returnitem");
        return_add_setReturnID.setText(returnID); //set return Id

        loadTable(); //to show all dvd details in table
        returnBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        late = new javax.swing.ButtonGroup();
        paymentPaid = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        return_add_isLateYe = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        return_add_setReturnID = new javax.swing.JLabel();
        return_add_getBorrowID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        returnBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        return_add_setIsLate = new javax.swing.JLabel();
        return_add_isPaymentPaidYes = new javax.swing.JRadioButton();
        return_add_isPaymentPaidNo = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        return_add_setReturnDate = new javax.swing.JLabel();
        return_add_setnumberOfDateLate = new javax.swing.JLabel();
        return_add_setFineAmount = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        return_add_getReturnID = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        return_find_searchID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        return_find_setReturnID = new javax.swing.JLabel();
        return_find_setBorrowID = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        return_find_setReturnDate = new javax.swing.JLabel();
        return_find_setIsLate = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        return_find_setNumberOfDateLate = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        return_find_setFineAmount = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        return_find_setFinePaymentPaid = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        return_userName = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        return_add_isLateYe.setBackground(new java.awt.Color(255, 255, 204));
        return_add_isLateYe.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        return_add_isLateYe.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Return ID :");

        return_add_setReturnID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        return_add_setReturnID.setText("R-000");

        return_add_getBorrowID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Borrow ID");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Return Date");

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setText("Is Late :");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Number Of Date Late");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Fine Amount");

        returnBtn.setBackground(new java.awt.Color(255, 204, 204));
        returnBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        returnBtn.setText("Return Complete");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Payment Paid :");

        return_add_setIsLate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        paymentPaid.add(return_add_isPaymentPaidYes);
        return_add_isPaymentPaidYes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        return_add_isPaymentPaidYes.setText("Yes");

        paymentPaid.add(return_add_isPaymentPaidNo);
        return_add_isPaymentPaidNo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        return_add_isPaymentPaidNo.setText("No");

        jButton4.setBackground(new java.awt.Color(204, 255, 255));
        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setText("Check Fine Payment");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        return_add_setReturnDate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        return_add_setnumberOfDateLate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        return_add_setFineAmount.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Item ID");

        return_add_getReturnID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel7)
                            .addComponent(jLabel20)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(return_add_setReturnID)
                            .addComponent(return_add_getBorrowID, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jButton4))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(return_add_isPaymentPaidYes)
                                .addGap(30, 30, 30)
                                .addComponent(return_add_isPaymentPaidNo))
                            .addComponent(return_add_setIsLate, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(return_add_setReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(return_add_setnumberOfDateLate, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(return_add_setFineAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(return_add_getReturnID, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(return_add_setReturnID))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(return_add_getBorrowID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(return_add_getReturnID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(return_add_setReturnDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(return_add_setIsLate))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(return_add_setnumberOfDateLate))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(return_add_setFineAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(return_add_isPaymentPaidYes)
                    .addComponent(return_add_isPaymentPaidNo))
                .addGap(18, 18, 18)
                .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );

        return_add_isLateYe.addTab("Return Item", jPanel3);

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setText("Search");
        jButton3.setPreferredSize(new java.awt.Dimension(79, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        return_find_searchID.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        return_find_searchID.setPreferredSize(new java.awt.Dimension(64, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_icon.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Return ID :");

        return_find_setReturnID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        return_find_setBorrowID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Borrow Id :");

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setText("Return Date :");

        return_find_setReturnDate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        return_find_setIsLate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setText("Is Late :");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Number Of Date Late :");

        return_find_setNumberOfDateLate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setText("Fine Amount :");

        return_find_setFineAmount.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Fine Payment Paid :");

        return_find_setFinePaymentPaid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(428, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(return_find_searchID, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel23)
                    .addComponent(jLabel12)
                    .addComponent(jLabel22)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(return_find_setReturnID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(return_find_setBorrowID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(return_find_setReturnDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(return_find_setIsLate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(return_find_setNumberOfDateLate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(return_find_setFineAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(return_find_setFinePaymentPaid))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(return_find_searchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(return_find_setReturnID))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(return_find_setBorrowID))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(return_find_setReturnDate))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(return_find_setIsLate))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(return_find_setNumberOfDateLate))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(return_find_setFineAmount))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(return_find_setFinePaymentPaid))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        return_add_isLateYe.addTab("Find Return Item", jPanel4);

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Return ID", "Borrow ID", "Return Date", "Is Late", "Late Dates", "Fine Amount", "Payment Paid"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
        );

        return_add_isLateYe.addTab("All Return Item", jPanel5);

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jButton1)
                .addContainerGap(665, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(return_add_isLateYe, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(return_add_isLateYe, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 934, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel17.setText("Library Master");

        return_userName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        return_userName.setText("name");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Hello,");

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel9.setText("Return Item");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(return_userName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(114, 114, 114)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(return_userName))))
                .addGap(19, 19, 19))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //navigate to dashboard
    private void backDashboard(String userName) {
        setVisible(false);

        DashboardFrame dashboard = new DashboardFrame(userName);
        dashboard.setVisible(true);
    }

    //back btn
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        backDashboard(userName);
    }//GEN-LAST:event_jButton1ActionPerformed

    /////////////////////////////////////////////////////////////////////// Make Return Item ///////////////////////////////////////////////////////////////
    //Implement to check emptyfield
    private void emptyFieldChecker(String borrowID) throws EmptyFieldException {

        if (borrowID.isEmpty()) {
            throw new EmptyFieldException("Your Fields are empty!!!\n Plese fill Your details");
        }

    }

//add a Return item
    private void addReturnItem(String returnID, String borrowID, String returnDate, String isLate, String numberOfDateLate, String fineAmount, String isFinePaymentPaid, String itemID) {
        DbConnection db = new DbConnection();

        String sql = "INSERT INTO returnitem(return_id,borrow_id,returnDate,isLate,numberOfDateLate,fineAmount,isFinePaymentPaid) VALUES(?,?,?,?,?,?,?)";
        String updateSql = "UPDATE borrowitem,returnitem,item SET borrowitem.isReturn=?,item.isAvailable=? WHERE returnitem.borrow_id=borrowitem.borrow_id AND borrowitem.item_id=item.item_id AND borrowitem.borrow_id=? AND item.item_id=?;";//to update item availability status

        try {
            PreparedStatement statement = db.getDbConnection().prepareStatement(sql);
            PreparedStatement statementUpdate = db.getDbConnection().prepareStatement(updateSql);

            statement.setString(1, returnID);
            statement.setString(2, borrowID);
            statement.setString(3, returnDate);
            statement.setString(4, isLate);
            statement.setString(5, numberOfDateLate);
            statement.setString(6, fineAmount);
            statement.setString(7, isFinePaymentPaid);

            statementUpdate.setString(1, "Yes");
            statementUpdate.setString(2, "Yes");
            statementUpdate.setString(3, borrowID);
            statementUpdate.setString(4, itemID);

            int row = statement.executeUpdate();
            int rowUpdate = statementUpdate.executeUpdate();

            if (row > 0 && rowUpdate > 0) {
                JOptionPane.showMessageDialog(null, "Return Item add sucessfully!!!", "Return Item", JOptionPane.INFORMATION_MESSAGE);
                backDashboard(userName);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Item Return Error", JOptionPane.ERROR_MESSAGE);
        }

    }

// make return complete btn
    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed

        String paymentPaid = "";

        if (return_add_isPaymentPaidYes.isSelected()) {
            paymentPaid = "Yes";  //check payment paid
        } else if (return_add_isPaymentPaidNo.isSelected()) {
            paymentPaid = "No";
        }

        ItemReturn returnItem = new ItemReturn(returnID, borrowID, returnDate, isLate, Integer.toString(numberOfDateLate), Integer.toString(fineAmount), paymentPaid, itemID);
        addReturnItem(returnItem.getReturn_id(), returnItem.getBorrow_id(), returnItem.getReturnDate(), returnItem.getIsLate(), returnItem.getNumberOfDateLate(), returnItem.getFineAmount(), returnItem.getIsFinePaymentPaid(), returnItem.getItemID());


    }//GEN-LAST:event_returnBtnActionPerformed

///////////////////////////////////////////////////////////////////////////////////////////////// find return item ///////////////////////////////////////////////////////////////////////////////////////////////
//implement to search return item from return id
    private void searchReturnItem(String searchId) throws NotFoundException {
        String returnID;
        String borrowID;
        String returnDate;
        String isLate;
        String numberOfDateLate;
        String fineAmount;
        String finePaymentPaid;

        DbConnection db = new DbConnection();
        String sql = "SELECT * FROM returnitem WHERE return_id=?;";
        try {
            PreparedStatement statement = db.getDbConnection().prepareStatement(sql);
            statement.setString(1, searchId);
            ResultSet result = statement.executeQuery();

            if (result.next()) {  // to find member
                returnID = result.getString("return_id");
                borrowID = result.getString("borrow_id");
                returnDate = result.getString("returnDate");
                isLate = result.getString("isLate");
                numberOfDateLate = result.getString("numberOfDateLate");
                fineAmount = result.getString("fineAmount");
                finePaymentPaid = result.getString("isFinePaymentPaid");

                return_find_setReturnID.setText(returnID);
                return_find_setBorrowID.setText(borrowID);
                return_find_setReturnDate.setText(returnDate);
                return_find_setIsLate.setText(isLate);
                return_find_setNumberOfDateLate.setText(numberOfDateLate);
                return_find_setFineAmount.setText(fineAmount);
                return_find_setFinePaymentPaid.setText(finePaymentPaid);

            } else {
                throw new NotFoundException(searchId + " not Found");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Find Return Item Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    //implement search return item btn
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String searchID = return_find_searchID.getText();

        try {
            searchReturnItem(searchID);
        } catch (NotFoundException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Find Return item error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
/////////////////////////////////////////////////////////////////////////////check fine payment ///////////////////////////////////////////////////////////////////////
    String dueDate;
    int numberOfDateLate;
    String isLate;
    int fineAmount;
    String borrowID;
    String itemID;

    //check nuber of date is late
    private int calulateLateDates(String dueDate, String returnDate) {

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy/MM/dd");

        LocalDate due = LocalDate.parse(dueDate, formatter);
        LocalDate returned = LocalDate.parse(returnDate, formatter);

        // Calculate the difference in days (returned - due)
        long lateDays = ChronoUnit.DAYS.between(due, returned);

        if (lateDays > 0) {
            return (int) lateDays;
        } else {
            return 0;
        }
    }

    //check fine payment btn
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        borrowID = return_add_getBorrowID.getText();
        itemID = return_add_getReturnID.getText();

        try {
            emptyFieldChecker(borrowID);//check empty field

            IDChecker checker = new IDChecker();
            checker.checkID(borrowID, "borrow_id", "borrowitem"); //check id validatity
            checker.checkID(itemID, "item_id", "item");

            DbConnection db = new DbConnection();
            String sql = "SELECT dueDate FROM borrowitem WHERE borrow_id=?;";

            PreparedStatement statement = db.getDbConnection().prepareStatement(sql);
            statement.setString(1, borrowID);
            ResultSet result = statement.executeQuery();
            if (result.next()) {
                dueDate = result.getString("dueDate"); // get item due date to calculate fine

                numberOfDateLate = calulateLateDates(dueDate, returnDate);

                if (numberOfDateLate == 0) {
                    isLate = "No";
                } else {
                    isLate = "Yes";
                }

                fineAmount = numberOfDateLate * 10;

                return_add_setReturnDate.setText(returnDate);
                return_add_setIsLate.setText(isLate);
                return_add_setnumberOfDateLate.setText(Integer.toString(numberOfDateLate));
                return_add_setFineAmount.setText(Integer.toString(fineAmount));
                return_add_isPaymentPaidNo.setSelected(true);

                returnBtn.setVisible(true);
            }

        } catch (EmptyFieldException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Return Item Empty Field Error", JOptionPane.ERROR_MESSAGE);
        } catch (IDnotValidException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "ID check error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "check fine payment error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    //////////////////////////////////////////////////////////// Load Table Section  ////////////////////////////////////////////////////////////////////////////////////////////////////////
// implement load all data in table
    private void loadTable() {
        String returnID;
        String borrowID;
        String returnDate;
        String isLate;
        String numberOfDateLate;
        String fineAmount;
        String finePaymentPaid;

        DbConnection db = new DbConnection();
        String sql = "SELECT * FROM returnitem;";
        try {
            PreparedStatement statement = db.getDbConnection().prepareStatement(sql);
            ResultSet result = statement.executeQuery();
            while (result.next()) {  // to llop all data
                returnID = result.getString("return_id");
                borrowID = result.getString("borrow_id");
                returnDate = result.getString("returnDate");
                isLate = result.getString("isLate");
                numberOfDateLate = result.getString("numberOfDateLate");
                fineAmount = result.getString("fineAmount");
                finePaymentPaid = result.getString("isFinePaymentPaid");

                //show data in table
                String data[] = {returnID, borrowID, returnDate, isLate, numberOfDateLate, fineAmount, finePaymentPaid};
                DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
                table.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Load Table Error", JOptionPane.ERROR_MESSAGE);
        }

    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ReturnItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ReturnItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ReturnItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ReturnItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ReturnItemForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.ButtonGroup late;
    private javax.swing.ButtonGroup paymentPaid;
    private javax.swing.JButton returnBtn;
    private javax.swing.JTextField return_add_getBorrowID;
    private javax.swing.JTextField return_add_getReturnID;
    private javax.swing.JTabbedPane return_add_isLateYe;
    private javax.swing.JRadioButton return_add_isPaymentPaidNo;
    private javax.swing.JRadioButton return_add_isPaymentPaidYes;
    private javax.swing.JLabel return_add_setFineAmount;
    private javax.swing.JLabel return_add_setIsLate;
    private javax.swing.JLabel return_add_setReturnDate;
    private javax.swing.JLabel return_add_setReturnID;
    private javax.swing.JLabel return_add_setnumberOfDateLate;
    private javax.swing.JTextField return_find_searchID;
    private javax.swing.JLabel return_find_setBorrowID;
    private javax.swing.JLabel return_find_setFineAmount;
    private javax.swing.JLabel return_find_setFinePaymentPaid;
    private javax.swing.JLabel return_find_setIsLate;
    private javax.swing.JLabel return_find_setNumberOfDateLate;
    private javax.swing.JLabel return_find_setReturnDate;
    private javax.swing.JLabel return_find_setReturnID;
    private javax.swing.JLabel return_userName;
    // End of variables declaration//GEN-END:variables

}
